// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.6.5_@types+node@20.4.5/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/robots.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-simple-robots@3.0.3/node_modules/nuxt-simple-robots/dist/runtime/server/robots-txt').default>>>>
    }
  }
}
export {}